import React from 'react';
import { motion } from 'framer-motion';
import { Footprints, Droplets, Moon, Activity, Flame, Check } from 'lucide-react';

// 🧠 SYSTEM 2: NUVYU TARGETS (PLAN)
// Lightweight, human-readable daily plan generated by future AI Reasoning Engine.
export const NuvyuTargets = React.memo(function NuvyuTargets({ gp, np, sp, targetCalories }: any) {
  return (
    <div className="space-y-3 px-1">
      <TargetItem icon={Footprints} text={`Walk ${gp.target_steps} Steps`} />
      <TargetItem icon={Droplets} text={`Drink ${gp.target_water / 1000}L Water`} />
      <TargetItem icon={Moon} text={`Sleep ${gp.target_sleep || 7.5} Hours Tonight`} />
      <TargetItem icon={Flame} text={`Burn ${targetCalories} kcal`} />
      <TargetItem icon={Activity} text={`Prioritize Recovery`} />
    </div>
  );
});

const TargetItem = ({ icon: Icon, text }: any) => (
  <div className="flex items-center gap-4 bg-[#050505]/40 border border-white/5 rounded-[16px] p-4">
    <div className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center shrink-0">
      <Icon size={16} className="text-white/70" />
    </div>
    <span className="text-[15px] font-medium text-white/90 tracking-tight">{text}</span>
  </div>
);

// 🧠 SYSTEM 3: TODAY'S PROGRESS (EXECUTION ENGINE)
// Reusable architecture for all future tracking integrations (Health Connect, Apple Health, Wearables).
export const TodayProgress = React.memo(function TodayProgress({ metrics, gp, np, sp, targetCalories }: any) {
  return (
    <div className="grid grid-cols-2 gap-3 px-1">
      <ProgressCard 
        icon={Footprints} title="Steps" 
        current={metrics.steps} target={gp.target_steps} 
        unit="" color="text-[#00FFA3]" 
      />
      <ProgressCard 
        icon={Droplets} title="Water" 
        current={metrics.water} target={gp.target_water} 
        unit="ml" color="text-blue-400" 
      />
      <ProgressCard 
        icon={Moon} title="Sleep" 
        current={metrics.sleep_hours || 0} target={gp.target_sleep || 7.5} 
        unit="h" color="text-indigo-400" 
      />
      <ProgressCard 
        icon={Activity} title="Recovery" 
        current={`${metrics.recovery_score || 0}`} target="100" 
        unit="%" color="text-purple-400" 
        subtitle={sp?.daily_strain_score > 30 ? 'High Strain' : 'Target Ready'} 
      />
      <ProgressCard 
        icon={Flame} title="Energy Burn" 
        current={metrics.energy_stats?.totalBurn || 0} target={targetCalories} 
        unit="kcal" color="text-orange-400" 
      />
      <ProgressCard 
        icon={Check} title="Protein" 
        current={np.protein_target_hit ? 'Hit' : 'Pending'} target="Goal" 
        unit="" color="text-pink-400" 
        subtitle={np.protein_target_hit ? 'Completed' : 'On Track'} 
      />
    </div>
  );
});

// Generic Progress Card UI Component (Logic-free)
const ProgressCard = ({ icon: Icon, title, current, target, unit, color, subtitle }: any) => {
  const safeCurrent = typeof current === 'number' ? current : parseFloat(current) || 0;
  const safeTarget = typeof target === 'number' ? target : parseFloat(target) || 1;
  const progress = Math.min(100, Math.max(0, (safeCurrent / safeTarget) * 100));

  return (
    <div className="bg-[#050505] border border-white/5 rounded-[20px] p-4 flex flex-col justify-between min-h-[120px]">
      <div className="flex items-center gap-2 mb-3">
        <Icon size={14} className={color} />
        <span className="text-white/60 text-[12px] font-medium tracking-tight">{title}</span>
      </div>
      <div className="flex items-end justify-between">
        <div>
          <div className="flex items-baseline gap-1">
            <span className="text-2xl font-semibold text-white tracking-tight">{current}</span>
            <span className="text-white/40 text-[11px] font-medium">{unit}</span>
          </div>
          <div className="text-white/40 text-[11px] font-medium mt-1">/ {target} {unit}</div>
        </div>
        {subtitle ? (
          <div className="text-right flex flex-col justify-end">
            <span className="text-[10px] font-medium text-white/40 uppercase tracking-widest">{subtitle}</span>
          </div>
        ) : (
          <div className="text-right flex flex-col justify-end">
            <span className="text-[14px] font-semibold text-white/90">{Math.round(progress)}%</span>
          </div>
        )}
      </div>
    </div>
  );
};
